### ISSUE TITLE
DB에 timestamp가 한국 시간이 아닌 외국 시간으로 찍히는 오류 수정

### ISSUE THREAD

**Issue by hyeong-jun-kim** [Geek-sasaeng/Geek_sasaeng-Server#113]
timestamp가 국내 시간이 아닌 해외 시간으로 찍혀 수정이 필요합니다.
수정 과정을 위 이슈에 올려주세요!

**Comment by KimMinheee** [comment]
ec2 인스턴스의 Timezone이 UTC로 설정되어 9시간 느리게 처리되고 있었습니다
Timezone 설정 변경하고 재부팅하여 해결 했습니다

참고한 사이트 url입니다
https://velog.io/@banjjoknim/EC2-%EC%84%9C%EB%B2%84-%EC%8B%9C%EA%B0%84-%EB%AC%B8%EC%A0%9C

**Comment by hyeong-jun-kim** [comment]
아하 ec2 timezone 이슈였군요 확인했습니다! 고생하셨어용
