### ISSUE TITLE
의존관계, 리스트 처리 관련 건의

### ISSUE THREAD

**Issue by hyeong-jun-kim** [Geek-sasaeng/Geek_sasaeng-Server#47]
DomitoryController - UniversityService - UniversityRepository 로 의존 관계가 맺어지는데 이렇게 진행해도 괜찮을까...?!
그리고 리스트는 스트림을 이용해 DTO로 바꿔줘서 리턴해주면 될 듯.. 그럼 JSON으로 바꿀 때 순환 참조 오류가 발생안하니까!

_Originally posted by @happysubin in https://github.com/Geek-sasaeng/Geek_sasaeng-Server/issues/45#issuecomment-1179529755_

**Comment by hyeong-jun-kim** [comment]
@happysubin DomitoryController - UniversityService - UniversityRepository 이렇게 의존관계가 설정되면 혹시 예상되는 문제점 같은게 어떤게 있는지 물어봐도 될까??

**Comment by happysubin** [comment]
괜히 DomitoryController에서 의존 관계가 늘어나는거지?? 단순히 의존 관계가 늘어나면 좋지 않으니까
그래서 그냥 UniversityController - UniversityService - UniversityRepository 로 하려다가 
기숙사를 다 긁어오는건데 UniversityController는 프론트가 이해하기 별로인 거 같아서..

**Comment by hyeong-jun-kim** [comment]
오.. 매우 디테일하구만 프론트가 보기 편하게 대학교 컨트롤러가 아닌, 기숙사 컨트롤러에 집어넣는거는 매우 찬성!! ㅎㅎ 데빈한테 하나 또 배워갑니다
