### ISSUE TITLE
Issue: diliveryParty-diliveryPartyproperty 연관관계 질문

### ISSUE THREAD

**Issue by hyeong-jun-kim** [Geek-sasaeng/Geek_sasaeng-Server#74]
diliveryParty에서 property를 1:1로 연관관계를 맺는게 맞을지, 1:N으로 맺는게 맞을지 논의하기 위한 스레드입니다.

**Comment by happysubin** [comment]
저는 배달 파티입장 말고 property의 입장으로도 봐야한다고 생각하는데 프로퍼티 입장에서는 1 : 1이 아닌 것 같다고 생각합니다!

**Comment by hyeong-jun-kim** [comment]
> 저는 배달 파티입장 말고 property의 입장으로도 봐야한다고 생각하는데 프로퍼티 입장에서는 1 : 1이 아닌 것 같다고 생각합니다!

저는 1:1이라고 생각하는데, 그 이유로는 property가 pk, 바로주문 status, 같이 먹자 status로 나뉘어져 있다고 하고 각 status는 Y,N으로 이루어진 Enum class로 이루어져 있다고 하면 배달 파티 게시글마다 property는 1개씩 할당받고 fk를 받아서 하면 되기 떄문이라고 생각했기 때문입니다.

로직 예시로 배달 파티 게시글 생성을 한다고 했을 때 먼저, property pk = 1, 바로주문 status = 'Y', 같이 먹자 = 'Y', 먼저 생성하고 그다음 배달파티에서 생성할 때 먼저 만들어진 property를 참고해 property fk로 1을 받아서 하면 1:1이 되지 않을까요??

**Comment by happysubin** [comment]
그럼 단순히 프로퍼티 테이블 컬럼이  id(pk), 바로주문 status, 같이 먹자 status 현재 이렇게 3개인가요?

**Comment by hyeong-jun-kim** [comment]
> 그럼 단순히 프로퍼티 테이블 컬럼이 id(pk), 바로주문 status, 같이 먹자 status 현재 이렇게 3개인가요?
네 원래 배달 파티에 하나로 묶어서 해도 괜찮지만 status가 추후에 많이 추가될 수 있어서 따로 테이블을 만들어서 관리하자는 느낌이였습니다

**Comment by KimMinheee** [comment]
저는 일대다(party:property)이면 객체 entity 관점에서 
Property(id, Party party, ImmediateOrderType immediateOrderType, WithPartyType withPartyType)
Party(id, List<Property> properties, 그외~)로 설계될거같은데 Party entity의 properties 리스트가 문제될 수 있을것 같습니다. 

일대일로 설계하면 (양방향 전제)
Property(id, Party party, ImmediateOrderType immediateOrderType, WithPartyType withPartyType),
Party(id, Property property)로 설계할 수 있을 것 같습니다.

객체의 장점을 백프로 활용한 방법은 아니지만 두 방법 중 하나를 택해야한다면 저는 일대일이 맞는것 같습니다!

**Comment by happysubin** [comment]
Property(id, Party party, ImmediateOrderType immediateOrderType, WithPartyType withPartyType)
만약에 그럼 프로퍼티 타입이 늘어난다면 컬럼이 추가되는건가요???

**Comment by KimMinheee** [comment]
넵 전 추가되는걸로 알고있습니다!

**Comment by hyeong-jun-kim** [comment]
프로퍼티 타입이 늘어나면 속성만 추가되고 컬럼은 추가 안되는게 아닌가용?

**Comment by happysubin** [comment]
제가 사태 진행 상황을 파악 못하다가 뒷북을 치는 거 같은데 ㅎㅎ.. 죄송합니다.
일단 컬럼을 추가하는 것은 결국에 테이블 구조를 변경하는 것인데 이는 좋지 못한 설계라고 생각합니다.

**Comment by hyeong-jun-kim** [comment]
흠 그렇긴 합니다 속성 하나를 추가하면 전체 컬럼에 영향을 주는거니까요 다른 좋은 대안 있을까요?

**Comment by happysubin** [comment]
제가 아침에 생각한 것은 일단 다음과 같습니다.
property talbe
id(pk), status
1, 오면 바로 먹어용
2, 같이 먹고 싶어요
3. (이제 계속 추가될 예정) 
4. //계속 이어진다...
이런 방식으로 테이블이 구성되는 줄 알고 이런 관점으로 계속 오늘 회의에서 발언을 했습니다.
또한 배달 파티 생성시에도
프로퍼티를 2개 주는 줄 알았습니다.(이건 무조건 정해져있다고 생각했습니다)
배달 파티 테이블 컬럼 2개 추가 == 배달 파티 엔티티 멤버 변수 2개 추가
그래서 저는 1 : N 이라는 발언을 했습니다.

**Comment by happysubin** [comment]
만약에 배달 파티에서 프로퍼티를 계속 추가할 수 있다면 결국 바람직한 설계는 M : N, 다대다가 맞다고 생각합니다

**Comment by KimMinheee** [comment]
저도 매번 컬럼을 추가하는건 좋지 않은 설계같고 다대다를 중간엔티티 둬서 해소하는게 나을것같습니다.....

**Comment by xhaktmchl** [comment]
나도 수빈이 이해한 거랑  똑같이 이해했는데 

다대다로 하면 저버 해시태그처럼 에러 나는거 아냐?

**Comment by happysubin** [comment]
미니가 저번에 다대다를 중간 테이블 두고 잘 풀었는데 그렇게 하면 에러 발생 안할거같으!!!
