### ISSUE TITLE
Http header에 token을 보관할 위치

### ISSUE THREAD

**Issue by happysubin** [Geek-sasaeng/Geek_sasaeng-Server#77]
보통 실무에서는 토큰은 authorization 헤더에  bearer access_token로 담습니다.
우리의 경우는 authorization 헤더에 bearer jwt_token을 담으면 됩니다. 

authorization bearer access_token로 검색하면 많은  자료가 나옵니다

**Comment by hyeong-jun-kim** [comment]
기존 jwt 헤더랑 bearer 방식이랑 어떻게 다른지 간단한 설명 부탁드려도 될까요??

**Comment by happysubin** [comment]
기존은 임의의 헤더? request.getHeader("X-ACCESS-TOKEN");에 담는데 jwt만 담는데 
좀 실전적인 형태는 Authorization에다가 Bearer jwtToken 형식이지

**Comment by KimMinheee** [comment]
찾아봤는데 일반적으로는 Authorization 헤더에 "Bearer " + "jwtToken" 을 담아서 요청을 보내는 경우가 많은 것 같습니다
 [
![BearerToken 헤더에 들어있는거 지움](https://user-images.githubusercontent.com/90172648/179338970-157d7dee-1638-499f-a9da-830097c76701.png)

]
이런 방식으로요!

**Comment by happysubin** [comment]
맞습니다. 실제로 많은 라이브러리에서 위와 같은 방식으로 입력을 받아(파라미터처럼) 내부에서 다 파싱해서 파싱한 값을 돌려줍니다.

**Comment by hyeong-jun-kim** [comment]
아하 저런 형식이군요 !! 이해 완료했습니다 감사합니다!! ㅎㅎ
