### ISSUE TITLE
API URL(Endpoint) 디자인 방식

### ISSUE THREAD

**Issue by happysubin** [Geek-sasaeng/Geek_sasaeng-Server#78]
1. /:domitoryId/delivery-parties?cursor=x
예시 https://geeksasaeng.shop/1/delivery-parties?cursor=0

2. /delivery-parties?cursor=1&domitoryId=1
https://geeksasaeng.shop/delivery-parties?cursor=0?dormitoryId=1

1번은 계층적으로 잘 짜여짐. 이미 프론트에서 연동을 하긴 한 듯?
2번은 포함 관계라고 애매하지면 URL이 깔끔한듯

**Comment by xhaktmchl** [comment]
수빈이 하는거 보니깐 1번 방식을 주로 쓰던데 보편적으로 많이 쓰여서 그런거야?
