### ISSUE TITLE
논의: autoIncrement로 기본키를 선언해도 괜찮을까요? 

### ISSUE THREAD

**Issue by hyeong-jun-kim** [Geek-sasaeng/Geek_sasaeng-Server#79]
학교 수다방을 보다가, 기본키로 autoIncrement 전략을 쓰면 하수라는 소리를 듣는다고(?) 실무에서는 varchar로 uuid를 생성해 기본키를 받는다고 합니다. 왜냐하면 **auto 전략을 쓰면 어느정도 가다가 다시 초기화 되어서 실무에서는 안쓰이고 연습용으로 많이 쓰인다고 해요.**
그래서 저희도 기본키를 uuid로 받을지, 아니면 그대로 autoIncrement로 할지 정해야될 것 같은데 의견 하나씩 적어주시면 감사하겠습니다.

**uuid 기본키 저장 참고 링크**: https://rnokhs.tistory.com/m/entry/JPA-UUID-varchar%EB%A1%9C-%EC%A0%80%EC%9E%A5%ED%95%98%EA%B8%B0

**Comment by xhaktmchl** [comment]
난 autoIncrement  에 한표입니다.
uuid가 중복되지 않는다곤 하지만 만약에 사용자가 기기변경이나 중고로 물건 구매하고 가입할 때 중복? 같은 트러블 생길 수 도? 있을거 같아.

**Comment by hyeong-jun-kim** [comment]
> 난 autoIncrement 에 한표입니다. uuid가 중복되지 않는다곤 하지만 만약에 사용자가 기기변경이나 중고로 물건 구매하고 가입할 때 중복? 같은 트러블 생길 수 도? 있을거 같아.

엄 여기서 UUID는 사용자 기기 식별 번호가 아니라 각 칼럼 생성시마다 나오는 랜덤 번호 같은 겁니다!! 그래서 그런 이유로는 겹치는 일은 발생하지 않을 것 같은데, 데빈 코멘트를 보고 생각해보니까 무게감 있는 서비스에 uuid를 제공하는게 맞는 것 같고, 저희 서비스는 ai 전략으로도 충분히 커버 가능할 것 같아서 autoIncrement 쓰는걸로 결정하면 좋을 것 같습니다 :)
다들 좋은 답변 달아주셔서 감사합니다!

**Comment by xhaktmchl** [comment]
굳굳 확인~~
