### ISSUE TITLE
URL 통합

### ISSUE THREAD

**Issue by happysubin** [Geek-sasaeng/Geek_sasaeng-Server#98]
현재 배달 파티 전체 조회 요청 URL은 다음과 같습니다.
1. /{dormitoryId}/delivery-parties?cursor=1 (예시)

제가 통합한 조건(배달 파티 인원, 배달 시간 대)을 기반으로 한 배달 파티 조회 요청 URL은 다음과 같습니다.
2. /{dormitoryId}/delivery-parties/conditions?cursor=2&orderTimeCategory=DINNER&maxMatching=10 (예시)

사실 그냥 
/{dormitoryId}/delivery-parties?cursor=1&orderTimeCategory=DINNER&maxMatching=10 (예시)
이렇게 통합하면 코드도 깔끔하고(메서드 중복 지우고, 응답 DTO 클래스 통합) 프론트도 요청하기 더 편할 거 같은데 어떻게 생각하시나여
쿼리스트링이 들어오는지에 관한 validation만 잘하면 이게 더 좋은 것 같습니당

**Comment by Juyeon0526** [comment]
깔끔하게 통합하는게 좋아보이네요
그럼 전체 조회랑 팔터 조회 모두 통합하는건가요?

**Comment by happysubin** [comment]
넹 전체 조회랑 필터를 합치고 검색어 부분은 일단 분리했습니다. 물론 검색어도 통합 가능합니당

**Comment by hyeong-jun-kim** [comment]
오오 매우 깔끔한 것 같아요! 저도 분리된 것 보다는 저렇게 통합해서 관리하는게 프론트한테도 편하고 더 깔끔한 것 같습니다 :)

**Comment by happysubin** [comment]
그럼 URL 통합하는 쪽으로 수정하겠습니다. 그리고 지금 테스트 데이터 배달 시간 주문이 동일한 것이 많아서 페이징을 하면 커서 1일때 2일때 중복 데이터가 나오는데, 제가 아이디를 기준으로 정렬했을때는 잘 동작하는 것을 확인했습니다. 나중에 테스트 데이터를 좀 퀄리티있게 수정하면 될 것 같습니다

**Comment by happysubin** [comment]
그래서 문득 든 생각은 DB에 초단위까지 넣는게 맞는 거 같기도 하고...

**Comment by hyeong-jun-kim** [comment]
엇 혹시 배달 시간 주문이 동일하면 중복 데이터가 나오는 이유를 알 수 있을까요??

**Comment by happysubin** [comment]
정렬을 배달 시간 주문(분 단위까지)으로 진행하는데 동일한 배달 시간 주문이 50개 있으니까 정렬할 때 문제가 있는 것 같습니당

**Comment by hyeong-jun-kim** [comment]
아 그러네요 그러면 정렬을 하는데 시간이 같으면 데빈이 말씀하신 아이디 알파벳순으로 정렬하면 될 것 같습니당!

**Comment by xhaktmchl** [comment]
아님 알파벳 순 말고 기본키 값으로 정렬하는건 어때?

**Comment by happysubin** [comment]
멤버 id로 하면 조인해야할 것 같아서 pk로 그냥 정렬했습니당

**Comment by xhaktmchl** [comment]
아니면 프론트에서 api요청할 때 현재시간에서 초만 조회해서 같이 넣어서 주면 따로 조건 알걸어도 될 것 같긴 해
